name: brokersfinal
services:
  - name: web
    git:
      branch: main
      repo_clone_url: [YOUR_GITHUB_REPO_URL]
    build_command: npm run build
    run_command: npm run serve
    envs:
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10 